name = "StructuredGrid"
uuid = "4573000b-1b0a-4bbb-a7b7-99f193844c6e"
authors = ["Christian Hauschel <hacs@zhaw.ch>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
